/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppLugaresRouteImport } from './routes/app.lugares'
import { Route as AppListaEsperaRouteImport } from './routes/app.lista-espera'
import { Route as AppInformesRouteImport } from './routes/app.informes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppInformesPorPrevisionRouteImport } from './routes/app.informes.por-prevision'
import { Route as AppInformesAtencionesDiariasRouteImport } from './routes/app.informes.atenciones-diarias'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppLugaresRoute = AppLugaresRouteImport.update({
  id: '/lugares',
  path: '/lugares',
  getParentRoute: () => AppRoute,
} as any)
const AppListaEsperaRoute = AppListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => AppRoute,
} as any)
const AppInformesRoute = AppInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppInformesPorPrevisionRoute = AppInformesPorPrevisionRouteImport.update({
  id: '/por-prevision',
  path: '/por-prevision',
  getParentRoute: () => AppInformesRoute,
} as any)
const AppInformesAtencionesDiariasRoute =
  AppInformesAtencionesDiariasRouteImport.update({
    id: '/atenciones-diarias',
    path: '/atenciones-diarias',
    getParentRoute: () => AppInformesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agenda': typeof AppAgendaRoute
  '/app/informes': typeof AppInformesRouteWithChildren
  '/app/lista-espera': typeof AppListaEsperaRoute
  '/app/lugares': typeof AppLugaresRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/informes/atenciones-diarias': typeof AppInformesAtencionesDiariasRoute
  '/app/informes/por-prevision': typeof AppInformesPorPrevisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agenda': typeof AppAgendaRoute
  '/app/informes': typeof AppInformesRouteWithChildren
  '/app/lista-espera': typeof AppListaEsperaRoute
  '/app/lugares': typeof AppLugaresRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/informes/atenciones-diarias': typeof AppInformesAtencionesDiariasRoute
  '/app/informes/por-prevision': typeof AppInformesPorPrevisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agenda': typeof AppAgendaRoute
  '/app/informes': typeof AppInformesRouteWithChildren
  '/app/lista-espera': typeof AppListaEsperaRoute
  '/app/lugares': typeof AppLugaresRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/informes/atenciones-diarias': typeof AppInformesAtencionesDiariasRoute
  '/app/informes/por-prevision': typeof AppInformesPorPrevisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/agenda'
    | '/app/informes'
    | '/app/lista-espera'
    | '/app/lugares'
    | '/app/pacientes'
    | '/app/informes/atenciones-diarias'
    | '/app/informes/por-prevision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/agenda'
    | '/app/informes'
    | '/app/lista-espera'
    | '/app/lugares'
    | '/app/pacientes'
    | '/app/informes/atenciones-diarias'
    | '/app/informes/por-prevision'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/agenda'
    | '/app/informes'
    | '/app/lista-espera'
    | '/app/lugares'
    | '/app/pacientes'
    | '/app/informes/atenciones-diarias'
    | '/app/informes/por-prevision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lugares': {
      id: '/app/lugares'
      path: '/lugares'
      fullPath: '/app/lugares'
      preLoaderRoute: typeof AppLugaresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lista-espera': {
      id: '/app/lista-espera'
      path: '/lista-espera'
      fullPath: '/app/lista-espera'
      preLoaderRoute: typeof AppListaEsperaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/informes': {
      id: '/app/informes'
      path: '/informes'
      fullPath: '/app/informes'
      preLoaderRoute: typeof AppInformesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/informes/por-prevision': {
      id: '/app/informes/por-prevision'
      path: '/por-prevision'
      fullPath: '/app/informes/por-prevision'
      preLoaderRoute: typeof AppInformesPorPrevisionRouteImport
      parentRoute: typeof AppInformesRoute
    }
    '/app/informes/atenciones-diarias': {
      id: '/app/informes/atenciones-diarias'
      path: '/atenciones-diarias'
      fullPath: '/app/informes/atenciones-diarias'
      preLoaderRoute: typeof AppInformesAtencionesDiariasRouteImport
      parentRoute: typeof AppInformesRoute
    }
  }
}

interface AppInformesRouteChildren {
  AppInformesAtencionesDiariasRoute: typeof AppInformesAtencionesDiariasRoute
  AppInformesPorPrevisionRoute: typeof AppInformesPorPrevisionRoute
}

const AppInformesRouteChildren: AppInformesRouteChildren = {
  AppInformesAtencionesDiariasRoute: AppInformesAtencionesDiariasRoute,
  AppInformesPorPrevisionRoute: AppInformesPorPrevisionRoute,
}

const AppInformesRouteWithChildren = AppInformesRoute._addFileChildren(
  AppInformesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppInformesRoute: typeof AppInformesRouteWithChildren
  AppListaEsperaRoute: typeof AppListaEsperaRoute
  AppLugaresRoute: typeof AppLugaresRoute
  AppPacientesRoute: typeof AppPacientesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppInformesRoute: AppInformesRouteWithChildren,
  AppListaEsperaRoute: AppListaEsperaRoute,
  AppLugaresRoute: AppLugaresRoute,
  AppPacientesRoute: AppPacientesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
